const RPC_URL = process.env.RPC_URL;
const REFLECT_BOT_ADDRESS = process.env.REFLECT_BOT_ADDRESS;
const KEEPER_BOT_ADDRESS = process.env.KEEPER_BOT_ADDRESS;
const DRIFT_ADMIN_SECRET_KEY = process.env.DRIFT_ADMIN_SECRET_KEY;
const JIT_BOT_ADDRESS = process.env.JIT_BOT_ADDRESS;
const SOL_PRICE_FEED = "0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d";
const JITO_PRICE_FEED = "0x67be9f519b95cf24338801051f9a808eff0a578ccb388db73b7f6fe1de019ffb";
const USDC_PRICE_FEED = "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a";

const AIRDROPS: string[] = [
    "JA72r7mb5uRpRqodhQCKsXWvKu7yLsAUKrz4N2kWmyRZ"
];

if (!DRIFT_ADMIN_SECRET_KEY) throw "Provide DRIFT_ADMIN_SECRET_KEY";
if (!REFLECT_BOT_ADDRESS) throw "Provide REFLECT_BOT_ADDRESS";
if (!RPC_URL) throw "Provide RPC_URL";
if (!KEEPER_BOT_ADDRESS) throw "Provide KEEPER_BOT_ADDRESS";
if (!JIT_BOT_ADDRESS) throw "Provide JIT_BOT_ADDRESS";
if (!SOL_PRICE_FEED) throw "Provide SOL_PRICE_FEED";
if (!JITO_PRICE_FEED) throw "Provide JITO_PRICE_FEED";


export {
    RPC_URL,
    REFLECT_BOT_ADDRESS,
    KEEPER_BOT_ADDRESS,
    JIT_BOT_ADDRESS,
    DRIFT_ADMIN_SECRET_KEY,
    SOL_PRICE_FEED,
    JITO_PRICE_FEED,
    USDC_PRICE_FEED,
    AIRDROPS
};